### ISSUE TITLE
Dankeschön!

### ISSUE THREAD

**Issue by mcmuller** [git-developer/fhem-examples#1]
Ich probiere schon seit Wochen an der Zeitauflösung letztes Reading -> aktuelles Reading rum - Dein Artikel hat mir "die Augen geöffnet". Ich lese per mqtt von openenergymonitor die aktuelle power von drei Phasen und wollte für die kWh-Berechung nicht extra das emoncms mitlaufen lassen. Jetzt kann ich die Pasehaddition und das power to kWh  ziemlich genau per userReadings berechnen.

Grüße,
Gregor

**Comment by git-developer** [comment]
Schön, dass es Dir hilft!
